# file:        Makefile
# author:      Andrea Vedaldi
# description: LaTeX --> pdf, html

.PHONY: all
all:
	make -C figures all

.PHONY: clean
clean:
	make -C figures clean

.PHONY: distclean
distclean: clean
	make -C figures distclean
