#!/bin/sh
# file:   vl-config
# brief:  VLFeat configuration script
# author: Andrea Vedaldi

# AUTORIGHTS

arch="VLARCH"
prefix="VLROOT"
version="VLVER"
cflags="VLCFLAGS"
execPrefix=""

function usage()
{
    usage="Usage: vl-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--arch[=ARCH]] [--version] [--cflags] [--libs]"
    echo "$usage"
    exit 1
}

function printParameters()
{
    while test $# -gt 0; do
        case $1 in
            --arch) echo "${arch}" ;;
            --prefix) echo "${prefix}" ;;
            --exec-prefix) echo "${execPrefix}" ;;
            --version) echo "${version}" ;;
            --cflags) echo "${cflags} -I\"${prefix}/vl\"" ;;
            --libs) echo "-L${execPrefix} -lvl"  ;;
            *) usage ;;
        esac
        shift
    done
}

if test $# -eq 0; then
    usage
fi

printargs=""

while test $# -gt 0; do
    case "$1" in
        -*=*) optarg=`echo "$1" | LC_ALL="C" sed 's/[-_a-zA-Z0-9]*=//'` ;;
        *) optarg= ;;
    esac
    case $1 in
        --arch=*) arch="${optarg}" ;;
        --prefix=*) prefix="${optarg}" ;;
        --exec-prefix=*) execPrefix="${optarg}" ;;
        *) printargs="${printargs} $1" ;;
    esac
    shift
done

if test -z "${execPrefix}" ;
then
    execPrefix="${prefix}/bin/${arch}"
fi

printParameters $printargs
